
export SOURCES = init/main.c \
					mm/heap/heap.c \
					mm/mm.c \
					rtl/list/list.c \
					rtl/stack/stack.c \
					init/parameters/parameters.c

x86_build :
		$(MAKE) -f makefile.x86 all

x86_clean :
		$(MAKE) -f makefile.x86 clean

x86_rebuild :
		$(MAKE) -f makefile.x86 rebuild
