
export SOURCES = init/main.c \
					mm/heap/heap.c \
					mm/mm.c \
					io/int_msg/int_msg.c \
					rtl/list/list.c \
					rtl/stack/stack.c \
					rtl/queue/queue.c \
					rtl/array_list/array_list.c \
					rtl/path/path.c \
					rtl/hash_table/hash_table.c \
					pm/pm.c \
					pm/mutex/mutex.c \
					init/parameters/parameters.c \
					msg/msg.c \
					vfs/vfs.c \
					vfs/om/om.c \
					vfs/om/devfs/devfs.c \
					vfs/fs/fs.c \
					vfs/fs/ramdisk/ramdisk.c \
					vfs/fs/tarfs/tarfs.c

x86_build :
		$(MAKE) -f makefile.x86 all

x86_clean :
		$(MAKE) -f makefile.x86 clean

x86_rebuild :
		$(MAKE) -f makefile.x86 rebuild
